# Producción multi-stage
FROM node:22.22-alpine3.22 AS build-stage
WORKDIR /app
RUN npm install -g pnpm@9

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

ENV NODE_ENV=production
RUN pnpm run build

FROM node:22.22-alpine3.22 AS production-stage
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

RUN addgroup -S nestapp && adduser -S nestapp -G nestapp

COPY --from=build-stage --chown=nestapp:nestapp /app/node_modules ./node_modules
COPY --from=build-stage --chown=nestapp:nestapp /app/dist ./dist
COPY --from=build-stage --chown=nestapp:nestapp /app/package.json ./package.json

USER nestapp
EXPOSE 3000
CMD ["node", "dist/main.js"]
