-- Data: permissions (formato module:action)

INSERT INTO permissions (name, module) VALUES
  ('users:read', 'users'),
  ('users:create', 'users'),
  ('users:update', 'users'),
  ('users:delete', 'users'),
  ('users:assign_roles', 'users'),
  ('roles:read', 'roles'),
  ('roles:create', 'roles'),
  ('roles:update', 'roles'),
  ('roles:delete', 'roles'),
  ('permissions:read', 'permissions'),
  ('businesses:read', 'businesses'),
  ('businesses:update', 'businesses'),
  ('services:read', 'services'),
  ('services:create', 'services'),
  ('services:update', 'services'),
  ('services:delete', 'services'),
  ('professionals:read', 'professionals'),
  ('professionals:create', 'professionals'),
  ('professionals:update', 'professionals'),
  ('professionals:delete', 'professionals'),
  ('availability:read', 'availability'),
  ('availability:update', 'availability'),
  ('appointments:read', 'appointments'),
  ('appointments:create', 'appointments'),
  ('appointments:update', 'appointments'),
  ('appointments:delete', 'appointments'),
  ('appointments:change_status', 'appointments'),
  ('clients:read', 'clients'),
  ('clients:create', 'clients'),
  ('clients:update', 'clients'),
  ('clients:delete', 'clients'),
  ('assets:read', 'assets'),
  ('assets:create', 'assets'),
  ('assets:update', 'assets'),
  ('assets:delete', 'assets'),
  ('audit_logs:read', 'audit_logs'),
  ('system:manage', 'system')
ON CONFLICT (name) DO NOTHING;
